version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      # Uncomment the line below if you want to use GPU support
      args:
        - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    container_name: barbershop